---
version: '3.8'

services:
 voting-app:
  image: dockersamples/examplevotingapp_vote
  ports:
   - 5050:80

 redis:
  image: redis
  ports:
   - 6379:6379

 worker:
  image: dockersamples/examplevotingapp_worker
  
 postgres:
  image: postgres
  ports: 
   - 5432:5432
  environment:
   POSTGRES_PASSWORD: intelliqit

 result-app:
  image: dockersamples/examplevotingapp_result
  ports:
   - 6060:80
...
